<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'commande_list' => [[], ['_controller' => 'App\\Controller\\ApiCommandeController::index'], [], [['text', '/api/commande/list']], [], []],
    'commande_post' => [[], ['_controller' => 'App\\Controller\\ApiCommandeController::create'], [], [['text', '/api/commande/post']], [], []],
    'commande_put' => [['id'], ['_controller' => 'App\\Controller\\ApiCommandeController::update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/commande/put']], [], []],
    'commande_delete' => [['id'], ['_controller' => 'App\\Controller\\ApiCommandeController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/commande/delete']], [], []],
];
