<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwC3nX7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwC3nX7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUwC3nX7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUwC3nX7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUwC3nX7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UwC3nX7',
    'container.build_id' => '864f6693',
    'container.build_time' => 1584480475,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwC3nX7');
